"""Add job_histories table

Revision ID: 0840341cd4b1
Revises: d5a2b3c4e6f7
Create Date: 2026-06-17 08:31:36.877020
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0840341cd4b1'
down_revision: str | None = 'd5a2b3c4e6f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_histories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('spec_type', sa.String(length=32), nullable=False),
    sa.Column('data_json', sa.JSON(), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_histories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_histories_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_histories_spec_type'), ['spec_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_histories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_histories_spec_type'))
        batch_op.drop_index(batch_op.f('ix_job_histories_job_id'))

    op.drop_table('job_histories')
    # ### end Alembic commands ###
