"""job chain fields

Revision ID: b454f4d7e3ae
Revises: 6614fe3f6118
Create Date: 2026-06-14 16:32:57.397574
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b454f4d7e3ae'
down_revision: str | None = '6614fe3f6118'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('with_screens', sa.Boolean(), server_default=sa.text('0'), nullable=False))
        batch_op.add_column(sa.Column('screen_spec_json', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('scenario_model', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('screen_spec_model', sa.String(length=128), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_column('screen_spec_model')
        batch_op.drop_column('scenario_model')
        batch_op.drop_column('screen_spec_json')
        batch_op.drop_column('with_screens')

    # ### end Alembic commands ###
